#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/gemma/modular_gemma.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_gemma.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2024 Google Inc. HuggingFace Inc. team. All rights reserved.
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 本脚本定义了Gemma模型的配置类GemmaConfig。Gemma是Google开发的一种大型语言模型。
# 该配置类用于存储和管理Gemma模型的各种参数设置，如词汇表大小、隐藏层维度、注意力头数量等。
# 通过这个配置类，用户可以初始化一个符合特定需求的Gemma模型实例，并控制模型的行为和输出。
# 该文件是自动从modular_gemma.py生成的，不应直接编辑，任何修改都应当在原始的modular_gemma.py文件中进行

from typing import Optional
from ...configuration_utils import PretrainedConfig


class GemmaConfig(PretrainedConfig):
    r"""
    This is the configuration class to store the configuration of a [`GemmaModel`]. It is used to instantiate an Gemma
    model according to the specified arguments, defining the model architecture. Instantiating a configuration with the
    defaults will yield a similar configuration to that of the Gemma-7B.
    e.g. [google/gemma-7b](https://huggingface.co/google/gemma-7b)
    Configuration objects inherit from [`PretrainedConfig`] and can be used to control the model outputs. Read the
    documentation from [`PretrainedConfig`] for more information.
    Args:
        vocab_size (`int`, *optional*, defaults to 256000):
            Vocabulary size of the Gemma model. Defines the number of different tokens that can be represented by the
            `inputs_ids` passed when calling [`GemmaModel`]
        hidden_size (`int`, *optional*, defaults to 3072):
            Dimension of the hidden representations.
        intermediate_size (`int`, *optional*, defaults to 24576):
            Dimension of the MLP representations.
        num_hidden_layers (`int`, *optional*, defaults to 28):
            Number of hidden layers in the Transformer decoder.
        num_attention_heads (`int`, *optional*, defaults to 16):
            Number of attention heads for each attention layer in the Transformer decoder.
        num_key_value_heads (`int`, *optional*, defaults to 16):
            This is the number of key_value heads that should be used to implement Grouped Query Attention. If
            `num_key_value_heads=num_attention_heads`, the model will use Multi Head Attention (MHA), if
            `num_key_value_heads=1` the model will use Multi Query Attention (MQA) otherwise GQA is used. When
            converting a multi-head checkpoint to a GQA checkpoint, each group key and value head should be constructed
            by meanpooling all the original heads within that group. For more details, check out [this
            paper](https://huggingface.co/papers/2305.13245). If it is not specified, will default to
            `num_attention_heads`.
        head_dim (`int`, *optional*, defaults to 256):
            The attention head dimension.
        hidden_act (`str` or `function`, *optional*, defaults to `"gelu_pytorch_tanh"`):
            The legacy activation function. It is overwritten by the `hidden_activation`.
        hidden_activation (`str` or `function`, *optional*):
            The non-linear activation function (function or string) in the decoder. Will default to `"gelu_pytorch_tanh"`
            if not specified. `"gelu_pytorch_tanh"` uses an approximation of the `"gelu"` activation function.
        max_position_embeddings (`int`, *optional*, defaults to 8192):
            The maximum sequence length that this model might ever be used with.
        initializer_range (`float`, *optional*, defaults to 0.02):
            The standard deviation of the truncated_normal_initializer for initializing all weight matrices.
        rms_norm_eps (`float`, *optional*, defaults to 1e-06):
            The epsilon used by the rms normalization layers.
        use_cache (`bool`, *optional*, defaults to `True`):
            Whether or not the model should return the last key/values attentions (not used by all models). Only
            relevant if `config.is_decoder=True`.
        pad_token_id (`int`, *optional*, defaults to 0):
            Padding token id.
        eos_token_id (`int`, *optional*, defaults to 1):
            End of stream token id.
        bos_token_id (`int`, *optional*, defaults to 2):
            Beginning of stream token id.
        tie_word_embeddings (`bool`, *optional*, defaults to `True`):
            Whether to tie weight embeddings
        rope_theta (`float`, *optional*, defaults to 10000.0):
            The base period of the RoPE embeddings.
        attention_bias (`bool`, defaults to `False`, *optional*, defaults to `False`):
            Whether to use a bias in the query, key, value and output projection layers during self-attention.
        attention_dropout (`float`, *optional*, defaults to 0.0):
            The dropout ratio for the attention probabilities.
        use_adarms (`bool`, *optional*, defaults to `False`):
            Whether to use ADARMS.
        adarms_cond_dim (`int`, *optional*, defaults to `None`):
            The dimension of the ADARMS condition.
    ```python
    >>> from transformers import GemmaModel, GemmaConfig
    >>> # Initializing a Gemma gemma-7b style configuration
    >>> configuration = GemmaConfig()
    >>> # Initializing a model from the gemma-7b style configuration
    >>> model = GemmaModel(configuration)
    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "gemma"    # 模型类型标识符
    keys_to_ignore_at_inference = ["past_key_values"]   # 推理时要忽略的键列表
    # 张量并行计划，定义了模型各层的并行策略
    base_model_tp_plan = {
        "layers.*.self_attn.q_proj": "colwise", # 自注意力层的查询投影层使用列并行
        "layers.*.self_attn.k_proj": "colwise",  # 自注意力层的键投影层使用列并行
        "layers.*.self_attn.v_proj": "colwise",  # 自注意力层的值投影层使用列并行
        "layers.*.self_attn.o_proj": "rowwise",  # 自注意力层的输出投影层使用行并行
        "layers.*.mlp.gate_proj": "colwise",    # 多层感知机层的门投影层使用列并行
        "layers.*.mlp.up_proj": "colwise",       # 多层感知机层的上投影层使用列并行
        "layers.*.mlp.down_proj": "rowwise",     # 多层感知机层的下投影层使用行并行
    }
    # 流水线并行计划，定义了模型各组件的输入输出
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]), # 嵌入层的输入输出
        "layers": (["hidden_states", "attention_mask"], ["hidden_states"]), # Transformer层的输入输出
        "norm": (["hidden_states"], ["hidden_states"]),     # 归一化层的输入输出
    }

    def __init__(
        self,
        vocab_size=256000,  # 词汇表大小
        hidden_size=3072,   # 隐藏层维度
        intermediate_size=24576,    # 中间层维度
        num_hidden_layers=28,   # 隐藏层数量
        num_attention_heads=16, # 注意力头数量
        num_key_value_heads=16, # 键值注意力头数量
        head_dim=256,           # 注意力头维度
        hidden_act="gelu_pytorch_tanh", # 隐藏层激活函数
        hidden_activation=None, # 隐藏层激活函数（优先级高于hidden_act）
        max_position_embeddings=8192,   # 最大位置嵌入长度
        initializer_range=0.02, # 初始化范围
        rms_norm_eps=1e-6,  # RMS归一化的epsilon值
        use_cache=True, # 是否使用缓存
        pad_token_id=0, # 填充标记ID
        eos_token_id=1, # 结束标记ID
        bos_token_id=2, # 开始标记ID
        tie_word_embeddings=True,   # 是否绑定词嵌入
        rope_theta=10000.0, # RoPE嵌入的基本周期
        attention_bias=False,   # 是否在注意力层使用偏置
        attention_dropout=0.0,  # 注意力丢弃率
        use_adarms: bool = False,   # 是否使用ADARMS
        adarms_cond_dim: Optional[int] = None,  # ADARMS条件维度
        **kwargs,
    ):
        """
        初始化GemmaConfig配置对象
        输入：
            所有参数都在英文文档字符串中有详细说明
        输出：
            无返回值，初始化配置对象的属性
        """
        self.vocab_size = vocab_size
        self.max_position_embeddings = max_position_embeddings
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.head_dim = head_dim
        self.num_key_value_heads = num_key_value_heads
        self.hidden_act = hidden_act
        self.hidden_activation = hidden_activation
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.use_cache = use_cache
        self.rope_theta = rope_theta
        self.attention_bias = attention_bias
        self.attention_dropout = attention_dropout
        self.use_adarms = use_adarms
        self.adarms_cond_dim = adarms_cond_dim

        # Set default for adarms_cond_dim if use_adarms is True
        if self.use_adarms and self.adarms_cond_dim is None:
            self.adarms_cond_dim = self.hidden_size

        super().__init__(
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )


__all__ = ["GemmaConfig"]   # d定义模块的公共接口，导出GemmaConfig类